//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.MockGeneratorServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="psc", Namespace="http://schemas.datacontract.org/2004/07/SB.MarketPromotions.MockGenerator")]
    [System.SerializableAttribute()]
    public partial class psc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.MockGeneratorServices.sc[] PopularSubcatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalMarketCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.MockGeneratorServices.sc[] PopularSubcat {
            get {
                return this.PopularSubcatField;
            }
            set {
                if ((object.ReferenceEquals(this.PopularSubcatField, value) != true)) {
                    this.PopularSubcatField = value;
                    this.RaisePropertyChanged("PopularSubcat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalMarketCount {
            get {
                return this.TotalMarketCountField;
            }
            set {
                if ((this.TotalMarketCountField.Equals(value) != true)) {
                    this.TotalMarketCountField = value;
                    this.RaisePropertyChanged("TotalMarketCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="sc", Namespace="http://schemas.datacontract.org/2004/07/SB.MarketPromotions.MockGenerator")]
    [System.SerializableAttribute()]
    public partial class sc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BetCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MarketCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SegmentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SortOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SubCategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubCategoryNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BetCount {
            get {
                return this.BetCountField;
            }
            set {
                if ((this.BetCountField.Equals(value) != true)) {
                    this.BetCountField = value;
                    this.RaisePropertyChanged("BetCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MarketCount {
            get {
                return this.MarketCountField;
            }
            set {
                if ((this.MarketCountField.Equals(value) != true)) {
                    this.MarketCountField = value;
                    this.RaisePropertyChanged("MarketCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SegmentId {
            get {
                return this.SegmentIdField;
            }
            set {
                if ((this.SegmentIdField.Equals(value) != true)) {
                    this.SegmentIdField = value;
                    this.RaisePropertyChanged("SegmentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SortOrder {
            get {
                return this.SortOrderField;
            }
            set {
                if ((this.SortOrderField.Equals(value) != true)) {
                    this.SortOrderField = value;
                    this.RaisePropertyChanged("SortOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SubCategoryId {
            get {
                return this.SubCategoryIdField;
            }
            set {
                if ((this.SubCategoryIdField.Equals(value) != true)) {
                    this.SubCategoryIdField = value;
                    this.RaisePropertyChanged("SubCategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubCategoryName {
            get {
                return this.SubCategoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SubCategoryNameField, value) != true)) {
                    this.SubCategoryNameField = value;
                    this.RaisePropertyChanged("SubCategoryName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MockGeneratorServices.IMockGeneratorServices")]
    public interface IMockGeneratorServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMockGeneratorServices/GetPopularSubCats", ReplyAction="http://tempuri.org/IMockGeneratorServices/GetPopularSubCatsResponse")]
        WebApplication1.MockGeneratorServices.psc GetPopularSubCats();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMockGeneratorServicesChannel : WebApplication1.MockGeneratorServices.IMockGeneratorServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MockGeneratorServicesClient : System.ServiceModel.ClientBase<WebApplication1.MockGeneratorServices.IMockGeneratorServices>, WebApplication1.MockGeneratorServices.IMockGeneratorServices {
        
        public MockGeneratorServicesClient() {
        }
        
        public MockGeneratorServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MockGeneratorServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MockGeneratorServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MockGeneratorServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebApplication1.MockGeneratorServices.psc GetPopularSubCats() {
            return base.Channel.GetPopularSubCats();
        }
    }
}
